#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'pickingNumbers' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY a as parameter.
#

def pickingNumbers(a):
    frequency = [0] * 101  # Assuming the maximum value in arr is 100
    max_length = 0
    
    for number in a:
        frequency[number] += 1
    
    for i in range(1, 101):
        max_length = max(max_length, frequency[i] + frequency[i-1])
    
    return max_length

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    a = list(map(int, input().rstrip().split()))

    result = pickingNumbers(a)

    fptr.write(str(result) + '\n')

    fptr.close()
